apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: ashok
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: caannamalai/config-server:3.2.4
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  namespace: ashok
  labels:
    app: configserver
spec:
  type: LoadBalancer 
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8888  
