apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  pull_request:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Pull Code and Build
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          apk add --no-cache git
          git clone https://github.com/cashokannamalai/springpetclinic-config-server-.git
          cd https://github.com/cashokannamalai/springpetclinic-config-server-.git
          echo "Pulled repository and switched to project directory"
